# This is a basic workflow that is manually triggered

name: cloudrun-deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
 setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@main


  
